name: rp2040 App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: Javier-varez/google-repo-action@v0.3
      with:
        manifest-url: 'Javier-varez/manifest'
        manifest-group: 'rp2040_app'
        checkout-deps: true
        generated-manifest: 'manifest.xml'
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.4
      with:
        release: '9-2020-q2'
    - name: make
      run: make -j

  clang_format:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: Javier-varez/google-repo-action@v0.3
      with:
        manifest-url: 'Javier-varez/manifest'
        manifest-group: 'rp2040_app'
        checkout-deps: true
    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: 'rp2040_app'
        clangFormatVersion: 10
